name: Print ENV and SECRET

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment value"
        required: true
        default: "development"

jobs:
  print-vars:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Print środo
        run: echo "Środowisko: ${{ github.event.inputs.environment }}"

      - name: Print ENV
        run: echo "ENVVAL = $ENV"

      - name: Print SECRET (base64 encoded)
        run: echo "SECRET=$(echo $SECRET | base64)"
        env:
          SECRET: ${{ secrets.SECRET }}


